const flags = {
    npcflag: [
        { bit: 1, name: "Gossip" },
        { bit: 2, name: "Quest Giver" },
        { bit: 4, name: "UNK1" },
        { bit: 8, name: "UNK2" },
        { bit: 16, name: "Trainer" },
        { bit: 32, name: "Class Trainer" },
        { bit: 64, name: "Profession Trainer" },
        { bit: 128, name: "Vendor" },
        { bit: 256, name: "Vendor Ammo" },
        { bit: 512, name: "Vendor Food" },
        { bit: 1024, name: "Vendor Poison" },
        { bit: 2048, name: "Vendor Reagent" },
        { bit: 4096, name: "Repairer" },
        { bit: 8192, name: "Flight Master" },
        { bit: 16384, name: "Spirit Healer" },
        { bit: 32768, name: "Spirit Guide" },
        { bit: 65536, name: "Innkeeper" },
        { bit: 131072, name: "Banker" },
        { bit: 262144, name: "Petitioner" },
        { bit: 524288, name: "Tabard Designer" },
        { bit: 1048576, name: "Battlemaster" },
        { bit: 2097152, name: "Auctioneer" },
        { bit: 4194304, name: "Stable Master" },
        { bit: 8388608, name: "Guild Banker" },
        { bit: 16777216, name: "Spellclick" },
        { bit: 67108864, name: "Mailbox" }
    ],
    unit_flags: [
        { bit: 1, name: "UNIT_FLAG_SERVER_CONTROLLED" },
        { bit: 2, name: "UNIT_FLAG_NON_ATTACKABLE" },
        { bit: 4, name: "UNIT_FLAG_DISABLE_MOVE" },
        { bit: 8, name: "UNIT_FLAG_PLAYER_CONTROLLED" },
        { bit: 16, name: "UNIT_FLAG_RENAME" },
        { bit: 32, name: "UNIT_FLAG_PREPARATION" },
        { bit: 64, name: "UNIT_FLAG_UNK_6" },
        { bit: 128, name: "UNIT_FLAG_NOT_ATTACKABLE_1" },
        { bit: 256, name: "UNIT_FLAG_IMMUNE_TO_PC" },
        { bit: 512, name: "UNIT_FLAG_IMMUNE_TO_NPC" },
        { bit: 1024, name: "UNIT_FLAG_LOOTING" },
        { bit: 2048, name: "UNIT_FLAG_PET_IN_COMBAT" },
        { bit: 4096, name: "UNIT_FLAG_PVP" },
        { bit: 8192, name: "UNIT_FLAG_SILENCED" },
        { bit: 16384, name: "UNIT_FLAG_CANNOT_SWIM" },
        { bit: 32768, name: "UNIT_FLAG_SWIMMING" },
        { bit: 65536, name: "UNIT_FLAG_NON_ATTACKABLE_2" },
        { bit: 131072, name: "UNIT_FLAG_PACIFIED" },
        { bit: 262144, name: "UNIT_FLAG_STUNNED" },
        { bit: 524288, name: "UNIT_FLAG_IN_COMBAT" },
        { bit: 1048576, name: "UNIT_FLAG_TAXI_FLIGHT" },
        { bit: 2097152, name: "UNIT_FLAG_DISARMED" },
        { bit: 4194304, name: "UNIT_FLAG_CONFUSED" },
        { bit: 8388608, name: "UNIT_FLAG_FLEEING" },
        { bit: 16777216, name: "UNIT_FLAG_POSSESSED" },
        { bit: 33554432, name: "UNIT_FLAG_NOT_SELECTABLE" },
        { bit: 67108864, name: "UNIT_FLAG_SKINNABLE" },
        { bit: 134217728, name: "UNIT_FLAG_MOUNT" },
        { bit: 268435456, name: "UNIT_FLAG_UNK_28" },
        { bit: 536870912, name: "UNIT_FLAG_PREVENT_EMOTES_FROM_CHAT_TEXT" },
        { bit: 1073741824, name: "UNIT_FLAG_SHEATHE" },
        { bit: 2147483648, name: "UNIT_FLAG_IMMUNE" }
    ],
    unit_flags2: [
        { bit: 1, name: "UNIT_FLAG2_FEIGN_DEATH" },
        { bit: 2, name: "UNIT_FLAG2_HIDE_BODY" },
        { bit: 4, name: "UNIT_FLAG2_IGNORE_REPUTATION" },
        { bit: 8, name: "UNIT_FLAG2_COMPREHEND_LANG" },
        { bit: 16, name: "UNIT_FLAG2_MIRROR_IMAGE" },
        { bit: 32, name: "UNIT_FLAG2_DO_NOT_FADE_IN" },
        { bit: 64, name: "UNIT_FLAG2_FORCE_MOVEMENT" },
        { bit: 128, name: "UNIT_FLAG2_DISARM_OFFHAND" },
        { bit: 256, name: "UNIT_FLAG2_DISABLE_PRED_STATS" },
        { bit: 1024, name: "UNIT_FLAG2_DISARM_RANGED" },
        { bit: 2048, name: "UNIT_FLAG2_REGENERATE_POWER" },
        { bit: 4096, name: "UNIT_FLAG2_RESTRICT_PARTY_INTERACTION" },
        { bit: 8192, name: "UNIT_FLAG2_PREVENT_SPELL_CLICK" },
        { bit: 16384, name: "UNIT_FLAG2_ALLOW_ENEMY_INTERACT" },
        { bit: 32768, name: "UNIT_FLAG2_CANNOT_TURN" },
        { bit: 65536, name: "UNIT_FLAG2_UNK2" },
        { bit: 131072, name: "UNIT_FLAG2_PLAY_DEATH_ANIM" },
        { bit: 262144, name: "UNIT_FLAG2_ALLOW_CHEAT_SPELLS" }
    ],
    unit_dynflag: [
        { bit: 0, name: "UNIT_DYNFLAG_NONE" },
        { bit: 1, name: "UNIT_DYNFLAG_LOOTABLE" },
        { bit: 2, name: "UNIT_DYNFLAG_TRACK_UNIT" },
        { bit: 4, name: "UNIT_DYNFLAG_TAPPED" },
        { bit: 8, name: "UNIT_DYNFLAG_TAPPED_BY_PLAYER" },
        { bit: 16, name: "UNIT_DYNFLAG_SPECIALINFO" },
        { bit: 32, name: "UNIT_DYNFLAG_DEAD" },
        { bit: 64, name: "UNIT_DYNFLAG_REFER_A_FRIEND" },
        { bit: 128, name: "UNIT_DYNFLAG_TAPPED_BY_ALL_THREAT_LIST" }
    ],
    type_flags: [
        { bit: 1, name: "CREATURE_TYPE_FLAG_TAMEABLE" },
        { bit: 2, name: "CREATURE_TYPE_FLAG_VISIBLE_TO_GHOSTS" },
        { bit: 4, name: "CREATURE_TYPE_FLAG_BOSS_MOB" },
        { bit: 8, name: "CREATURE_TYPE_FLAG_DO_NOT_PLAY_WOUND_PARRY_ANIMATION" },
        { bit: 16, name: "CREATURE_TYPE_FLAG_NO_FACTION_TOOLTIP" },
        { bit: 32, name: "CREATURE_TYPE_FLAG_MORE_AUDIBLE" },
        { bit: 64, name: "CREATURE_TYPE_FLAG_SPELL_ATTACKABLE" },
        { bit: 128, name: "CREATURE_TYPE_FLAG_INTERACT_WHILE_DEAD" },
        { bit: 256, name: "CREATURE_TYPE_FLAG_SKIN_WITH_HERBALISM" },
        { bit: 512, name: "CREATURE_TYPE_FLAG_SKIN_WITH_MINING" },
        { bit: 1024, name: "CREATURE_TYPE_FLAG_NO_DEATH_MESSAGE" },
        { bit: 2048, name: "CREATURE_TYPE_FLAG_ALLOW_MOUNTED_COMBAT" },
        { bit: 4096, name: "CREATURE_TYPE_FLAG_CAN_ASSIST" },
        { bit: 8192, name: "CREATURE_TYPE_FLAG_NO_PET_BAR" },
        { bit: 16384, name: "CREATURE_TYPE_FLAG_MASK_UID" },
        { bit: 32768, name: "CREATURE_TYPE_FLAG_SKIN_WITH_ENGINEERING" },
        { bit: 65536, name: "CREATURE_TYPE_FLAG_TAMEABLE_EXOTIC" },
        { bit: 131072, name: "CREATURE_TYPE_FLAG_USE_MODEL_COLLISION_SIZE" },
        { bit: 262144, name: "CREATURE_TYPE_FLAG_ALLOW_INTERACTION_WHILE_IN_COMBAT" },
        { bit: 524288, name: "CREATURE_TYPE_FLAG_COLLIDE_WITH_MISSILES" },
        { bit: 1048576, name: "CREATURE_TYPE_FLAG_NO_NAME_PLATE" },
        { bit: 2097152, name: "CREATURE_TYPE_FLAG_DO_NOT_PLAY_MOUNTED_ANIMATIONS" },
        { bit: 4194304, name: "CREATURE_TYPE_FLAG_IS_LINK_ALL" },
        { bit: 8388608, name: "CREATURE_TYPE_FLAG_INTERACT_ONLY_WITH_CREATOR" },
        { bit: 16777216, name: "CREATURE_TYPE_FLAG_DO_NOT_PLAY_UNIT_EVENT_SOUNDS" },
        { bit: 33554432, name: "CREATURE_TYPE_FLAG_HAS_NO_SHADOW_BLOB" },
        { bit: 67108864, name: "CREATURE_TYPE_FLAG_TREAT_AS_RAID_UNIT" },
        { bit: 134217728, name: "CREATURE_TYPE_FLAG_FORCE_GOSSIP" },
        { bit: 268435456, name: "CREATURE_TYPE_FLAG_DO_NOT_SHEATHE" },
        { bit: 536870912, name: "CREATURE_TYPE_FLAG_DO_NOT_TARGET_ON_INTERACTION" },
        { bit: 1073741824, name: "CREATURE_TYPE_FLAG_DO_NOT_RENDER_OBJECT_NAME" },
        { bit: 2147483648, name: "CREATURE_TYPE_FLAG_UNIT_IS_QUEST_BOSS" }
    ],
    mechanic_immune_mask: [
        { bit: 1, name: "MECHANIC_CHARM" },
        { bit: 2, name: "MECHANIC_DISORIENTED" },
        { bit: 4, name: "MECHANIC_DISARM" },
        { bit: 8, name: "MECHANIC_DISTRACT" },
        { bit: 16, name: "MECHANIC_FEAR" },
        { bit: 32, name: "MECHANIC_GRIP" },
        { bit: 64, name: "MECHANIC_ROOT" },
        { bit: 128, name: "MECHANIC_SLOW_ATTACK" },
        { bit: 256, name: "MECHANIC_SILENCE" },
        { bit: 512, name: "MECHANIC_SLEEP" },
        { bit: 1024, name: "MECHANIC_SNARE" },
        { bit: 2048, name: "MECHANIC_STUN" },
        { bit: 4096, name: "MECHANIC_FREEZE" },
        { bit: 8192, name: "MECHANIC_KNOCKOUT" },
        { bit: 16384, name: "MECHANIC_BLEED" },
        { bit: 32768, name: "MECHANIC_BANDAGE" },
        { bit: 65536, name: "MECHANIC_POLYMORPH" },
        { bit: 131072, name: "MECHANIC_BANISH" },
        { bit: 262144, name: "MECHANIC_SHIELD" },
        { bit: 524288, name: "MECHANIC_SHACKLE" },
        { bit: 1048576, name: "MECHANIC_MOUNT" },
        { bit: 2097152, name: "MECHANIC_INFECTED" },
        { bit: 4194304, name: "MECHANIC_TURN" },
        { bit: 8388608, name: "MECHANIC_HORROR" },
        { bit: 16777216, name: "MECHANIC_INVULNERABILITY" },
        { bit: 33554432, name: "MECHANIC_INTERRUPT" },
        { bit: 67108864, name: "MECHANIC_DAZE" },
        { bit: 134217728, name: "MECHANIC_DISCOVERY" },
        { bit: 268435456, name: "MECHANIC_IMMUNE_SHIELD" },
        { bit: 536870912, name: "MECHANIC_SAPPED" },
        { bit: 1073741824, name: "MECHANIC_ENRAGED" }
    ],
    SchoolMask: [
        { bit: 1, name: "SPELL_SCHOOL_MASK_NORMAL" },
        { bit: 2, name: "SPELL_SCHOOL_MASK_HOLY" },
        { bit: 4, name: "SPELL_SCHOOL_MASK_FIRE" },
        { bit: 8, name: "SPELL_SCHOOL_MASK_NATURE" },
        { bit: 16, name: "SPELL_SCHOOL_MASK_FROST" },
        { bit: 32, name: "SPELL_SCHOOL_MASK_SHADOW" },
        { bit: 64, name: "SPELL_SCHOOL_MASK_ARCANE" }
    ],
    DispelTypeMask: [
        { bit: 2, name: "DISPEL_MAGIC" },
        { bit: 4, name: "DISPEL_CURSE" },
        { bit: 8, name: "DISPEL_DISEASE" },
        { bit: 16, name: "DISPEL_POISON" },
        { bit: 32, name: "DISPEL_STEALTH" },
        { bit: 64, name: "DISPEL_INVISIBILITY" },
        { bit: 128, name: "DISPEL_ALL" },
        { bit: 256, name: "DISPEL_SPE_NPC_ONLY" },
        { bit: 512, name: "DISPEL_ENRAGE" },
        { bit: 1024, name: "DISPEL_ZG_TICKET" },
        { bit: 2048, name: "DESPEL_OLD_UNUSED" }
    ],
    MechanicsMask: [
        { bit: 2, name: "MECHANIC_CHARM" },
        { bit: 4, name: "MECHANIC_DISORIENTED" },
        { bit: 8, name: "MECHANIC_DISARM" },
        { bit: 16, name: "MECHANIC_DISTRACT" },
        { bit: 32, name: "MECHANIC_FEAR" },
        { bit: 64, name: "MECHANIC_GRIP" },
        { bit: 128, name: "MECHANIC_ROOT" },
        { bit: 256, name: "MECHANIC_SLOW_ATTACK" },
        { bit: 512, name: "MECHANIC_SILENCE" },
        { bit: 1024, name: "MECHANIC_SLEEP" },
        { bit: 2048, name: "MECHANIC_SNARE" },
        { bit: 4096, name: "MECHANIC_STUN" },
        { bit: 8192, name: "MECHANIC_FREEZE" },
        { bit: 16384, name: "MECHANIC_KNOCKOUT" },
        { bit: 32768, name: "MECHANIC_BLEED" },
        { bit: 65536, name: "MECHANIC_BANDAGE" },
        { bit: 131072, name: "MECHANIC_POLYMORPH" },
        { bit: 262144, name: "MECHANIC_BANISH" },
        { bit: 524288, name: "MECHANIC_SHIELD" },
        { bit: 1048576, name: "MECHANIC_SHACKLE" },
        { bit: 2097152, name: "MECHANIC_MOUNT" },
        { bit: 4194304, name: "MECHANIC_INFECTED" },
        { bit: 8388608, name: "MECHANIC_TURN" },
        { bit: 16777216, name: "MECHANIC_HORROR" },
        { bit: 33554432, name: "MECHANIC_INVULNERABILITY" },
        { bit: 67108864, name: "MECHANIC_INTERRUPT" },
        { bit: 134217728, name: "MECHANIC_DAZE" },
        { bit: 268435456, name: "MECHANIC_DISCOVERY" },
        { bit: 536870912, name: "MECHANIC_IMMUNE_SHIELD" },
        { bit: 1073741824, name: "MECHANIC_SAPPED" },
        { bit: 2147483648, name: "MECHANIC_ENRAGED" },
        { bit: 4294967296, name: "MECHANIC_WOUNDED" },
        { bit: 8589934592, name: "MECHANIC_INFECTED_2" },
        { bit: 17179869184, name: "MECHANIC_INFECTED_3" },
        { bit: 34359738368, name: "MECHANIC_INFECTED_4" },
        { bit: 68719476736, name: "MECHANIC_TAUNTED" }
    ],
    spellschoolmask: [
        { bit: 1, name: "SPELL_SCHOOL_MASK_NORMAL" },
        { bit: 2, name: "SPELL_SCHOOL_MASK_HOLY" },
        { bit: 4, name: "SPELL_SCHOOL_MASK_FIRE" },
        { bit: 8, name: "SPELL_SCHOOL_MASK_NATURE" },
        { bit: 16, name: "SPELL_SCHOOL_MASK_FROST" },
        { bit: 32, name: "SPELL_SCHOOL_MASK_SHADOW" },
        { bit: 64, name: "SPELL_SCHOOL_MASK_ARCANE" }
    ],
    flags_extra: [
        { bit: 1, name: "CREATURE_FLAG_EXTRA_INSTANCE_BIND" },
        { bit: 2, name: "CREATURE_FLAG_EXTRA_CIVILIAN" },
        { bit: 4, name: "CREATURE_FLAG_EXTRA_NO_PARRY" },
        { bit: 8, name: "CREATURE_FLAG_EXTRA_NO_PARRY_HASTEN" },
        { bit: 16, name: "CREATURE_FLAG_EXTRA_NO_BLOCK" },
        { bit: 32, name: "CREATURE_FLAG_EXTRA_NO_CRUSHING_BLOWS" },
        { bit: 64, name: "CREATURE_FLAG_EXTRA_NO_XP" },
        { bit: 128, name: "CREATURE_FLAG_EXTRA_TRIGGER" },
        { bit: 256, name: "CREATURE_FLAG_EXTRA_NO_TAUNT" },
        { bit: 512, name: "CREATURE_FLAG_EXTRA_NO_MOVE_FLAGS_UPDATE" },
        { bit: 1024, name: "CREATURE_FLAG_EXTRA_GHOST_VISIBILITY" },
        { bit: 2048, name: "CREATURE_FLAG_EXTRA_USE_OFFHAND_ATTACK" },
        { bit: 4096, name: "CREATURE_FLAG_EXTRA_NO_SELL_VENDOR" },
        { bit: 8192, name: "CREATURE_FLAG_EXTRA_IGNORE_COMBAT" },
        { bit: 16384, name: "CREATURE_FLAG_EXTRA_WORLDEVENT" },
        { bit: 32768, name: "CREATURE_FLAG_EXTRA_GUARD" },
        { bit: 65536, name: "CREATURE_FLAG_EXTRA_IGNORE_FEIGN_DEATH" },
        { bit: 131072, name: "CREATURE_FLAG_EXTRA_NO_CRIT" },
        { bit: 262144, name: "CREATURE_FLAG_EXTRA_NO_SKILL_GAINS" },
        { bit: 524288, name: "CREATURE_FLAG_EXTRA_OBEYS_TAUNT_DIMINISHING_RETURNS" },
        { bit: 1048576, name: "CREATURE_FLAG_EXTRA_ALL_DIMINISH" },
        { bit: 2097152, name: "CREATURE_FLAG_EXTRA_NO_PLAYER_DAMAGE_REQ" },
        { bit: 4194304, name: "CREATURE_FLAG_EXTRA_AVOID_AOE" },
        { bit: 8388608, name: "CREATURE_FLAG_EXTRA_NO_DODGE" },
        { bit: 16777216, name: "CREATURE_FLAG_EXTRA_MODULE" },
        { bit: 33554432, name: "CREATURE_FLAG_EXTRA_DONT_CALL_ASSISTANCE" },
        { bit: 67108864, name: "CREATURE_FLAG_EXTRA_IGNORE_ALL_ASSISTANCE_CALLS" },
        { bit: 134217728, name: "CREATURE_FLAG_EXTRA_DONT_OVERRIDE_SAI_ENTRY" },
        { bit: 268435456, name: "CREATURE_FLAG_EXTRA_DUNGEON_BOSS" },
        { bit: 536870912, name: "CREATURE_FLAG_EXTRA_IGNORE_PATHFINDING" },
        { bit: 1073741824, name: "CREATURE_FLAG_EXTRA_IMMUNITY_KNOCKBACK" },
        { bit: 2147483648, name: "CREATURE_FLAG_EXTRA_HARD_RESET" }
    ],
    racemask: [
        { bit: 1, name: "RACE_HUMAN" },
        { bit: 2, name: "RACE_ORC" },
        { bit: 4, name: "RACE_DWARF" },
        { bit: 8, name: "RACE_NIGHTELF" },
        { bit: 16, name: "RACE_UNDEAD_PLAYER" },
        { bit: 32, name: "RACE_TAUREN" },
        { bit: 64, name: "RACE_GNOME" },
        { bit: 128, name: "RACE_TROLL" },
        { bit: 256, name: "RACE_GOBLIN" },
        { bit: 512, name: "RACE_BLOODELF" },
        { bit: 1024, name: "RACE_DRAENEI" },
        { bit: 2048, name: "RACE_FEL_ORC" },
        { bit: 4096, name: "RACE_NAGA" },
        { bit: 8192, name: "RACE_BROKEN" },
        { bit: 16384, name: "RACE_SKELETON" },
        { bit: 32768, name: "RACE_VRYKUL" },
        { bit: 65536, name: "RACE_TUSKARR" },
        { bit: 131072, name: "RACE_FOREST_TROLL" },
        { bit: 262144, name: "RACE_TAUNKA" },
        { bit: 524288, name: "RACE_NORTHREND_SKELETON" },
        { bit: 1048576, name: "RACE_ICE_TROLL" }
    ],
    classmask: [
        { bit: 1, name: "CLASS_WARRIOR" },
        { bit: 2, name: "CLASS_PALADIN" },
        { bit: 4, name: "CLASS_HUNTER" },
        { bit: 8, name: "CLASS_ROGUE" },
        { bit: 16, name: "CLASS_PRIEST" },
        { bit: 32, name: "CLASS_DEATH_KNIGHT" },
        { bit: 64, name: "CLASS_SHAMAN" },
        { bit: 128, name: "CLASS_MAGE" },
        { bit: 256, name: "CLASS_WARLOCK" },
        { bit: 512, name: "CLASS_UNK" },
        { bit: 1024, name: "CLASS_DRUID" }
    ],
    dispelmask: [
        { bit: 2, name: "DISPEL_MAGIC" },
        { bit: 4, name: "DISPEL_CURSE" },
        { bit: 8, name: "DISPEL_DISEASE" },
        { bit: 16, name: "DISPEL_POISON" },
        { bit: 32, name: "DISPEL_STEALTH" },
        { bit: 64, name: "DISPEL_INVISIBILITY" },
        { bit: 128, name: "DISPEL_ALL" },
        { bit: 256, name: "DISPEL_SPE_NPC_ONLY" },
        { bit: 512, name: "DISPEL_ENRAGE" },
        { bit: 1024, name: "DISPEL_ZG_TICKET" },
        { bit: 2048, name: "DESPEL_OLD_UNUSED" }
    ],
    spellattr0: [
        { bit: 1, name: "SPELL_ATTR0_PROC_FAILURE_BURNS_CHARGE" },
        { bit: 2, name: "SPELL_ATTR0_USES_RANGED_SLOT" },
        { bit: 4, name: "SPELL_ATTR0_ON_NEXT_SWING_NO_DAMAGE" },
        { bit: 8, name: "SPELL_ATTR0_DO_NOT_LOG_IMMUNE_MISSES" },
        { bit: 16, name: "SPELL_ATTR0_IS_ABILITY" },
        { bit: 32, name: "SPELL_ATTR0_IS_TRADESKILL" },
        { bit: 64, name: "SPELL_ATTR0_PASSIVE" },
        { bit: 128, name: "SPELL_ATTR0_DO_NOT_DISPLAY" },
        { bit: 256, name: "SPELL_ATTR0_DO_NOT_LOG" },
        { bit: 512, name: "SPELL_ATTR0_HELD_ITEM_ONLY" },
        { bit: 1024, name: "SPELL_ATTR0_ON_NEXT_SWING" },
        { bit: 2048, name: "SPELL_ATTR0_WEARER_CASTS_PROC_TRIGGER" },
        { bit: 4096, name: "SPELL_ATTR0_SERVER_ONLY" },
        { bit: 8192, name: "SPELL_ATTR0_ALLOW_ITEM_SPELL_IN_PVP" },
        { bit: 16384, name: "SPELL_ATTR0_ONLY_INDOORS" },
        { bit: 32768, name: "SPELL_ATTR0_ONLY_OUTDOORS" },
        { bit: 65536, name: "SPELL_ATTR0_NOT_SHAPESHIFTED" },
        { bit: 131072, name: "SPELL_ATTR0_ONLY_STEALTHED" },
        { bit: 262144, name: "SPELL_ATTR0_DO_NOT_SHEATH" },
        { bit: 524288, name: "SPELL_ATTR0_SCALES_WITH_CREATURE_LEVEL" },
        { bit: 1048576, name: "SPELL_ATTR0_CANCELS_AUTO_ATTACK_COMBAT" },
        { bit: 2097152, name: "SPELL_ATTR0_NO_ACTIVE_DEFENSE" },
        { bit: 4194304, name: "SPELL_ATTR0_TRACK_TARGET_IN_CAST_PLAYER_ONLY" },
        { bit: 8388608, name: "SPELL_ATTR0_ALLOW_CAST_WHILE_DEAD" },
        { bit: 16777216, name: "SPELL_ATTR0_ALLOW_WHILE_MOUNTED" },
        { bit: 33554432, name: "SPELL_ATTR0_COOLDOWN_ON_EVENT" },
        { bit: 67108864, name: "SPELL_ATTR0_AURA_IS_DEBUFF" },
        { bit: 134217728, name: "SPELL_ATTR0_ALLOW_WHILE_SITTING" },
        { bit: 268435456, name: "SPELL_ATTR0_NOT_IN_COMBAT_ONLY_PEACEFUL" },
        { bit: 536870912, name: "SPELL_ATTR0_NO_IMMUNITIES" },
        { bit: 1073741824, name: "SPELL_ATTR0_HEARTBEAT_RESIST" },
        { bit: 2147483648, name: "SPELL_ATTR0_NO_AURA_CANCEL" }
    ],
    spellcustomattr: [
        { bit: 1, name: "SPELL_ATTR0_CU_ENCHANT_PROC" },
        { bit: 2, name: "SPELL_ATTR0_CU_CONE_BACK" },
        { bit: 4, name: "SPELL_ATTR0_CU_CONE_LINE" },
        { bit: 8, name: "SPELL_ATTR0_CU_SHARE_DAMAGE" },
        { bit: 16, name: "SPELL_ATTR0_CU_NO_INITIAL_THREAT" },
        { bit: 32, name: "SPELL_ATTR0_CU_AURA_CC" },
        { bit: 64, name: "SPELL_ATTR0_CU_DONT_BREAK_STEALTH" },
        { bit: 128, name: "SPELL_ATTR0_CU_NO_PVP_FLAG" },
        { bit: 256, name: "SPELL_ATTR0_CU_DIRECT_DAMAGE" },
        { bit: 512, name: "SPELL_ATTR0_CU_CHARGE" },
        { bit: 1024, name: "SPELL_ATTR0_CU_PICKPOCKET" },
        { bit: 2048, name: "SPELL_ATTR0_CU_IGNORE_EVADE" },
        { bit: 4096, name: "SPELL_ATTR0_CU_NEGATIVE_EFF0" },
        { bit: 8192, name: "SPELL_ATTR0_CU_NEGATIVE_EFF1" },
        { bit: 16384, name: "SPELL_ATTR0_CU_NEGATIVE_EFF2" },
        { bit: 32768, name: "SPELL_ATTR0_CU_IGNORE_ARMOR" },
        { bit: 65536, name: "SPELL_ATTR0_CU_REQ_TARGET_FACING_CASTER" },
        { bit: 131072, name: "SPELL_ATTR0_CU_REQ_CASTER_BEHIND_TARGET" },
        { bit: 262144, name: "SPELL_ATTR0_CU_ALLOW_INFLIGHT_TARGET" },
        { bit: 524288, name: "SPELL_ATTR0_CU_NEEDS_AMMO_DATA" },
        { bit: 1048576, name: "SPELL_ATTR0_CU_BINARY_SPELL" },
        { bit: 2097152, name: "SPELL_ATTR0_CU_NO_POSITIVE_TAKEN_BONUS" },
        { bit: 4194304, name: "SPELL_ATTR0_CU_SINGLE_AURA_STACK" },
        { bit: 8388608, name: "SPELL_ATTR0_CU_SCHOOLMASK_NORMAL_WITH_MAGIC" },
        { bit: 16777216, name: "SPELL_ATTR0_CU_AURA_CANNOT_BE_SAVED" },
        { bit: 33554432, name: "SPELL_ATTR0_CU_POSITIVE_EFF0" },
        { bit: 67108864, name: "SPELL_ATTR0_CU_POSITIVE_EFF1" },
        { bit: 134217728, name: "SPELL_ATTR0_CU_POSITIVE_EFF2" },
        { bit: 268435456, name: "SPELL_ATTR0_CU_FORCE_SEND_CATEGORY_COOLDOWNS" },
        { bit: 536872960, name: "SPELL_ATTR0_CU_FORCE_AURA_SAVING" },
        { bit: 536870912, name: "SPELL_ATTR0_CU_ONLY_ONE_AREA_AURA" },
        { bit: 1073741824, name: "SPELL_ATTR0_CU_ENCOUNTER_REWARD" },
        { bit: 2147483648, name: "SPELL_ATTR0_CU_BYPASS_MECHANIC_IMMUNITY" }        
    ],
    spellattr1: [
        { bit: 1, name: "SPELL_ATTR1_DISMISS_PET_FIRST" },
        { bit: 2, name: "SPELL_ATTR1_USE_ALL_MANA" },
        { bit: 4, name: "SPELL_ATTR1_IS_CHANNELED" },
        { bit: 8, name: "SPELL_ATTR1_NO_REDIRECTION" },
        { bit: 16, name: "SPELL_ATTR1_NO_SKILL_INCREASE" },
        { bit: 32, name: "SPELL_ATTR1_ALLOW_WHILE_STEALTHED" },
        { bit: 64, name: "SPELL_ATTR1_IS_SELF_CHANNELED" },
        { bit: 128, name: "SPELL_ATTR1_NO_REFLECTION" },
        { bit: 256, name: "SPELL_ATTR1_ONLY_PEACEFUL_TARGETS" },
        { bit: 512, name: "SPELL_ATTR1_INITIATE_COMBAT" },
        { bit: 1024, name: "SPELL_ATTR1_NO_THREAT" },
        { bit: 2048, name: "SPELL_ATTR1_AURA_UNIQUE" },
        { bit: 4096, name: "SPELL_ATTR1_FAILURE_BREAKS_STEALTH" },
        { bit: 8192, name: "SPELL_ATTR1_TOGGLE_FAR_SIGHT" },
        { bit: 16384, name: "SPELL_ATTR1_TRACK_TARGET_IN_CHANNEL" },
        { bit: 32768, name: "SPELL_ATTR1_IMMUNITY_PURGES_EFFECT" },
        { bit: 65536, name: "SPELL_ATTR1_IMMUNITY_TO_HOSTILE_AND_FRIENDLY_EFFECTS" },
        { bit: 131072, name: "SPELL_ATTR1_NO_AUTOCAST_AI" },
        { bit: 262144, name: "SPELL_ATTR1_PREVENTS_ANIM" },
        { bit: 524288, name: "SPELL_ATTR1_EXCLUDE_CASTER" },
        { bit: 1048576, name: "SPELL_ATTR1_FINISHING_MOVE_DAMAGE" },
        { bit: 2097152, name: "SPELL_ATTR1_THREAT_ONLY_ON_MISS" },
        { bit: 4194304, name: "SPELL_ATTR1_FINISHING_MOVE_DURATION" },
        { bit: 8388608, name: "SPELL_ATTR1_IGNORE_OWNERS_DEATH" },
        { bit: 16777216, name: "SPELL_ATTR1_SPECIAL_SKILLUP" },
        { bit: 33554432, name: "SPELL_ATTR1_AURA_STAYS_AFTER_COMBAT" },
        { bit: 67108864, name: "SPELL_ATTR1_REQUIRE_ALL_TARGETS" },
        { bit: 134217728, name: "SPELL_ATTR1_DISCOUNT_POWER_ON_MISS" },
        { bit: 268435456, name: "SPELL_ATTR1_NO_AURA_ICON" },
        { bit: 536870912, name: "SPELL_ATTR1_NAME_IN_CHANNEL_BAR" },
        { bit: 1073741824, name: "SPELL_ATTR1_COMBO_ON_BLOCK" },
        { bit: 2147483648, name: "SPELL_ATTR1_CAST_WHEN_LEARNED" }
    ],
    spellattr2: [
        { bit: 1, name: "SPELL_ATTR2_ALLOW_DEAD_TARGET" },
        { bit: 2, name: "SPELL_ATTR2_NO_SHAPESHIFT_UI" },
        { bit: 4, name: "SPELL_ATTR2_IGNORE_LINE_OF_SIGHT" },
        { bit: 8, name: "SPELL_ATTR2_ALLOW_LOW_LEVEL_BUFF" },
        { bit: 16, name: "SPELL_ATTR2_USE_SHAPESHIFT_BAR" },
        { bit: 32, name: "SPELL_ATTR2_AUTO_REPEAT" },
        { bit: 64, name: "SPELL_ATTR2_CANNOT_CAST_ON_TAPPED" },
        { bit: 128, name: "SPELL_ATTR2_DO_NOT_REPORT_SPELL_FAILURE" },
        { bit: 256, name: "SPELL_ATTR2_INCLUDE_IN_ADVANCED_COMBAT_LOG" },
        { bit: 512, name: "SPELL_ATTR2_ALWAYS_CAST_AS_UNIT" },
        { bit: 1024, name: "SPELL_ATTR2_SPECIAL_TAMING_FLAG" },
        { bit: 2048, name: "SPELL_ATTR2_NO_TARGET_PER_SECOND_COST" },
        { bit: 4096, name: "SPELL_ATTR2_CHAIN_FROM_CASTER" },
        { bit: 8192, name: "SPELL_ATTR2_ENCHANT_OWN_ITEM_ONLY" },
        { bit: 16384, name: "SPELL_ATTR2_ALLOW_WHILE_INVISIBLE" },
        { bit: 32768, name: "SPELL_ATTR2_DO_NOT_CONSUME_IF_GAINED_DURING_CAST" },
        { bit: 65536, name: "SPELL_ATTR2_NO_ACTIVE_PETS" },
        { bit: 131072, name: "SPELL_ATTR2_DO_NOT_RESET_COMBAT_TIMERS" },
        { bit: 262144, name: "SPELL_ATTR2_NO_JUMP_WHILE_CAST_PENDING" },
        { bit: 524288, name: "SPELL_ATTR2_ALLOW_WHILE_NOT_SHAPESHIFTED" },
        { bit: 1048576, name: "SPELL_ATTR2_INITIATE_COMBAT_POST_CAST" },
        { bit: 2097152, name: "SPELL_ATTR2_FAIL_ON_ALL_TARGETS_IMMUNE" },
        { bit: 4194304, name: "SPELL_ATTR2_NO_INITIAL_THREAD" },
        { bit: 8388608, name: "SPELL_ATTR2_PROC_COOLDOWN_ON_FAILURE" },
        { bit: 16777216, name: "SPELL_ATTR2_ITEM_CAST_WITH_OWNER_SKILL" },
        { bit: 33554432, name: "SPELL_ATTR2_DONT_BLOCK_MANA_REGEN" },
        { bit: 67108864, name: "SPELL_ATTR2_NO_SCHOOL_IMMUNITIES" },
        { bit: 134217728, name: "SPELL_ATTR2_IGNORE_WEAPONSKILL" },
        { bit: 268435456, name: "SPELL_ATTR2_NOT_AN_ACTION" },
        { bit: 536870912, name: "SPELL_ATTR2_CANT_CRIT" },
        { bit: 1073741824, name: "SPELL_ATTR2_ACTIVE_THREAT" },
        { bit: 2147483648, name: "SPELL_ATTR2_RETAIN_ITEM_CAST" }
    ],
    spellattr3: [
        { bit: 1, name: "SPELL_ATTR3_PVP_ENABLING" },
        { bit: 2, name: "SPELL_ATTR3_NO_PROC_EQUIP_REQUIREMENT" },
        { bit: 4, name: "SPELL_ATTR3_NO_CASTING_BAR_TEXT" },
        { bit: 8, name: "SPELL_ATTR3_COMPLETELY_BLOCKED" },
        { bit: 16, name: "SPELL_ATTR3_NO_RES_TIMER" },
        { bit: 32, name: "SPELL_ATTR3_NO_DURABILITY_LOSS" },
        { bit: 64, name: "SPELL_ATTR3_NO_AVOIDANCE" },
        { bit: 128, name: "SPELL_ATTR3_DOT_STACKING_RULE" },
        { bit: 256, name: "SPELL_ATTR3_ONLY_ON_PLAYER" },
        { bit: 512, name: "SPELL_ATTR3_NOT_A_PROC" },
        { bit: 1024, name: "SPELL_ATTR3_REQUIRES_MAIN_HAND_WEAPON" },
        { bit: 2048, name: "SPELL_ATTR3_ONLY_BATTLEGROUNDS" },
        { bit: 4096, name: "SPELL_ATTR3_ONLY_ON_GHOSTS" },
        { bit: 8192, name: "SPELL_ATTR3_HIDE_CHANNEL_BAR" },
        { bit: 16384, name: "SPELL_ATTR3_HIDE_IN_RAID_FILTER" },
        { bit: 32768, name: "SPELL_ATTR3_NORMAL_RANGED_ATTACK" },
        { bit: 65536, name: "SPELL_ATTR3_SUPPRESS_CASTER_PROCS" },
        { bit: 131072, name: "SPELL_ATTR3_SUPPRESS_TARGET_PROCS" },
        { bit: 262144, name: "SPELL_ATTR3_ALWAYS_HIT" },
        { bit: 524288, name: "SPELL_ATTR3_INSTANT_TARGET_PROCS" },
        { bit: 1048576, name: "SPELL_ATTR3_ALLOW_AURA_WHILE_DEAD" },
        { bit: 2097152, name: "SPELL_ATTR3_ONLY_PROC_OUTDOORS" },
        { bit: 4194304, name: "SPELL_ATTR3_CASTING_CANCELS_AUTOREPEAT" },
        { bit: 8388608, name: "SPELL_ATTR3_NO_DAMAGE_HISTORY" },
        { bit: 16777216, name: "SPELL_ATTR3_REQUIRES_OFF_HAND_WEAPON" },
        { bit: 33554432, name: "SPELL_ATTR3_TREAT_AS_PERIODIC" },
        { bit: 67108864, name: "SPELL_ATTR3_CAN_PROC_FROM_PROCS" },
        { bit: 134217728, name: "SPELL_ATTR3_ONLY_PROC_ON_CASTER" },
        { bit: 268435456, name: "SPELL_ATTR3_IGNORE_CASTER_AND_TARGET_RESTRICTIONS" },
        { bit: 536870912, name: "SPELL_ATTR3_IGNORE_CASTER_MODIFIERS" },
        { bit: 1073741824, name: "SPELL_ATTR3_DO_NOT_DISPLAY_RANGE" },
        { bit: 2147483648, name: "SPELL_ATTR3_NOT_ON_AOE_IMMUNE" }
    ],
    spellattr4: [
        { bit: 1, name: "SPELL_ATTR4_NO_CAST_LOG" },
        { bit: 2, name: "SPELL_ATTR4_CLASS_TRIGGER_ONLY_ON_TARGET" },
        { bit: 4, name: "SPELL_ATTR4_AURA_EXPIRES_OFFLINE" },
        { bit: 8, name: "SPELL_ATTR4_NO_HELPFUL_THREAT" },
        { bit: 16, name: "SPELL_ATTR4_NO_HARMFUL_THREAT" },
        { bit: 32, name: "SPELL_ATTR4_ALLOW_CLIENT_TARGETING" },
        { bit: 64, name: "SPELL_ATTR4_CANNOT_BE_STOLEN" },
        { bit: 128, name: "SPELL_ATTR4_ALLOW_CAST_WHILE_CASTING" },
        { bit: 256, name: "SPELL_ATTR4_IGNORE_DAMAGE_TAKEN_MODIFIERS" },
        { bit: 512, name: "SPELL_ATTR4_COMBAT_FEEDBACK_WHEN_USABLE" },
        { bit: 1024, name: "SPELL_ATTR4_WEAPON_SPEED_COST_SCALING" },
        { bit: 2048, name: "SPELL_ATTR4_NO_PARTIAL_IMMUNITY" },
        { bit: 4096, name: "SPELL_ATTR4_AURA_IS_BUFF" },
        { bit: 8192, name: "SPELL_ATTR4_DO_NOT_LOG_CASTER" },
        { bit: 16384, name: "SPELL_ATTR4_REACTIVE_DAMAGE_PROC" },
        { bit: 32768, name: "SPELL_ATTR4_NOT_IN_SPELLBOOK" },
        { bit: 65536, name: "SPELL_ATTR4_NOT_IN_ARENA_OR_RATED_BATTLEGROUND" },
        { bit: 131072, name: "SPELL_ATTR4_IGNORE_DEFAULT_ARENA_RESTRICTIONS" },
        { bit: 262144, name: "SPELL_ATTR4_BOUNCY_CHAIN_MISSILES" },
        { bit: 524288, name: "SPELL_ATTR4_ALLOW_PROC_WHILE_SITTING" },
        { bit: 1048576, name: "SPELL_ATTR4_AURA_NEVER_BOUNCES" },
        { bit: 2097152, name: "SPELL_ATTR4_ALLOW_ENETRING_ARENA" },
        { bit: 4194304, name: "SPELL_ATTR4_PROC_SUPPRESS_SWING_ANIM" },
        { bit: 8388608, name: "SPELL_ATTR4_SUPPRESS_WEAPON_PROCS" },
        { bit: 16777216, name: "SPELL_ATTR4_AUTO_RANGED_COMBAT" },
        { bit: 33554432, name: "SPELL_ATTR4_OWNER_POWER_SCALING" },
        { bit: 67108864, name: "SPELL_ATTR4_ONLY_FLYING_AREAS" },
        { bit: 134217728, name: "SPELL_ATTR4_FORCE_DISPLAY_CASTBAR" },
        { bit: 268435456, name: "SPELL_ATTR4_IGNORE_COMBAT_TIMERS" },
        { bit: 536870912, name: "SPELL_ATTR4_AURA_BOUNCE_FAILS_SPELL" },
        { bit: 1073741824, name: "SPELL_ATTR4_OBSOLETE" },
        { bit: 2147483648, name: "SPELL_ATTR4_USE_FACING_FROM_SPELL" }
    ],
    spellattr5: [
        { bit: 1, name: "SPELL_ATTR5_ALLOW_ACTION_DURING_CHANNEL" },
        { bit: 2, name: "SPELL_ATTR5_NO_REAGENT_COST_WITH_AURA" },
        { bit: 4, name: "SPELL_ATTR5_REMOVE_ENTERING_ARENA" },
        { bit: 8, name: "SPELL_ATTR5_ALLOW_WHILE_STUNNED" },
        { bit: 16, name: "SPELL_ATTR5_TRIGGERS_CHANNELING" },
        { bit: 32, name: "SPELL_ATTR5_LIMIT_N" },
        { bit: 64, name: "SPELL_ATTR5_IGNORE_AREA_EFFECT_PVP_CHECK" },
        { bit: 128, name: "SPELL_ATTR5_NOT_ON_PLAYER" },
        { bit: 256, name: "SPELL_ATTR5_NOT_ON_PLAYER_CONTROLLED_NPC" },
        { bit: 512, name: "SPELL_ATTR5_EXTRA_INITIAL_PERIOD" },
        { bit: 1024, name: "SPELL_ATTR5_DO_NOT_DISPLAY_DURATION" },
        { bit: 2048, name: "SPELL_ATTR5_IMPLIED_TARGETING" },
        { bit: 4096, name: "SPELL_ATTR5_MELEE_CHAIN_TARGETING" },
        { bit: 8192, name: "SPELL_ATTR5_SPELL_HASTE_AFFECTS_PERIODIC" },
        { bit: 16384, name: "SPELL_ATTR5_NOT_AVALIABLE_WHILE_CHARMED" },
        { bit: 32768, name: "SPELL_ATTR5_TREAT_AS_AREA_EFFECT" },
        { bit: 65536, name: "SPELL_ATTR5_AURA_AFFECTS_NOT_JUST_REQ_EQUIPPED_ITEM" },
        { bit: 131072, name: "SPELL_ATTR5_ALLOW_WHILE_FLEEING" },
        { bit: 262144, name: "SPELL_ATTR5_ALLOW_WHILE_CONFUSED" },
        { bit: 524288, name: "SPELL_ATTR5_AI_DOESNT_FACE_TARGET" },
        { bit: 1048576, name: "SPELL_ATTR5_DO_NOT_ATTEMPT_A_PET_RESUMMON_WHEN_DISMOUNTING" },
        { bit: 2097152, name: "SPELL_ATTR5_IGNORE_TARGET_REQUIREMENTS" },
        { bit: 4194304, name: "SPELL_ATTR5_NOT_ON_TRIVIAL" },
        { bit: 8388608, name: "SPELL_ATTR5_NO_PARTIAL_RESISTS" },
        { bit: 16777216, name: "SPELL_ATTR5_IGNORE_CASTER_REQUIREMENETS" },
        { bit: 33554432, name: "SPELL_ATTR5_ALWAYS_LINE_OF_SIGHT" },
        { bit: 67108864, name: "SPELL_ATTR5_ALWAYS_AOE_LINE_OF_SIGHT" },
        { bit: 134217728, name: "SPELL_ATTR5_NO_CASTER_AURA_ICON" },
        { bit: 268435456, name: "SPELL_ATTR5_NO_TARGET_AURA_ICON" },
        { bit: 536870912, name: "SPELL_ATTR5_AURA_UNIQUE_PER_CASTER" },
        { bit: 1073741824, name: "SPELL_ATTR5_ALWAYS_SHOW_GROUND_TEXTURE" },
        { bit: 2147483648, name: "SPELL_ATTR5_ADD_MELEE_HIT_RATING" }
    ],
    spellattr6: [
        { bit: 1, name: "SPELL_ATTR6_NO_COOLDOWN_ON_TOOLTIP" },
        { bit: 2, name: "SPELL_ATTR6_DO_NOT_RESET_COOLDOWN_IN_ARENA" },
        { bit: 4, name: "SPELL_ATTR6_NOT_AN_ATTACK" },
        { bit: 8, name: "SPELL_ATTR6_CAN_ASSIST_IMMUNE_PC" },
        { bit: 16, name: "SPELL_ATTR6_IGNORE_FOR_MOD_TIME_RATE" },
        { bit: 32, name: "SPELL_ATTR6_DO_NOT_CONSUME_RESOURCES" },
        { bit: 64, name: "SPELL_ATTR6_FLOATING_COMBAT_TEXT_ON_CAST" },
        { bit: 128, name: "SPELL_ATTR6_AURA_IS_WEAPON_PROC" },
        { bit: 256, name: "SPELL_ATTR6_DO_NOT_CHAIN_TO_CROWD_CONTROLLED_TARGETS" },
        { bit: 512, name: "SPELL_ATTR6_ALLOW_ON_CHARMED_TARGETS" },
        { bit: 1024, name: "SPELL_ATTR6_NO_AURA_LOG" },
        { bit: 2048, name: "SPELL_ATTR6_NOT_IN_RAID_INSTANCES" },
        { bit: 4096, name: "SPELL_ATTR6_ALLOW_WHILE_RIDING_VEHICLE" },
        { bit: 8192, name: "SPELL_ATTR6_IGNORE_PHASE_SHIFT" },
        { bit: 16384, name: "SPELL_ATTR6_AI_PRIMARY_RANGED_ATTACK" },
        { bit: 32768, name: "SPELL_ATTR6_NO_PUSHBACK" },
        { bit: 65536, name: "SPELL_ATTR6_NO_JUMP_PATHING" },
        { bit: 131072, name: "SPELL_ATTR6_ALLOW_EQUIP_WHILE_CASTING" },
        { bit: 262144, name: "SPELL_ATTR6_ORIGINATE_FROM_CONTROLLER" },
        { bit: 524288, name: "SPELL_ATTR6_DELAY_COMBAT_TIMER_DURING_CAST" },
        { bit: 1048576, name: "SPELL_ATTR6_AURA_ICON_ONLY_FOR_CASTER" },
        { bit: 2097152, name: "SPELL_ATTR6_SHOW_MECHANIC_AS_COMBAT_TEXT" },
        { bit: 4194304, name: "SPELL_ATTR6_ABSORB_CANNOT_BE_IGNORED" },
        { bit: 8388608, name: "SPELL_ATTR6_TAPS_IMMEDIATELY" },
        { bit: 16777216, name: "SPELL_ATTR6_CAN_TARGET_UNTARGETABLE" },
        { bit: 33554432, name: "SPELL_ATTR6_DOESNT_RESET_SWING_TIMER_IF_INSTANT" },
        { bit: 67108864, name: "SPELL_ATTR6_VEHICLE_IMMUNITY_CATEGORY" },
        { bit: 134217728, name: "SPELL_ATTR6_IGNORE_HEALTH_MODIFIERS" },
        { bit: 268435456, name: "SPELL_ATTR6_DO_NOT_SELECT_TARGET_WITH_INITIATES_COMBAT" },
        { bit: 536870912, name: "SPELL_ATTR6_IGNORE_CASTER_DAMAGE_MODIFIERS" },
        { bit: 1073741824, name: "SPELL_ATTR6_DISABLE_TIED_EFFECT_POINTS" },
        { bit: 2147483648, name: "SPELL_ATTR6_NO_CATEGORY_COOLDOWN_MODS" }
    ],
    spellattr7: [
        { bit: 1, name: "SPELL_ATTR7_ALLOW_SPELL_REFLECTION" },
        { bit: 2, name: "SPELL_ATTR7_NO_TARGET_DURATION_MOD" },
        { bit: 4, name: "SPELL_ATTR7_DISABLE_AURA_WHILE_DEAD" },
        { bit: 8, name: "SPELL_ATTR7_DEBUG_SPELL" },
        { bit: 16, name: "SPELL_ATTR7_TREAT_AS_RAID_BUFF" },
        { bit: 32, name: "SPELL_ATTR7_CAN_BE_MULTI_CAST" },
        { bit: 64, name: "SPELL_ATTR7_DONT_CAUSE_SPELL_PUSHBACK" },
        { bit: 128, name: "SPELL_ATTR7_PREPARE_FOR_VEHICLE_CONTROL_END" },
        { bit: 256, name: "SPELL_ATTR7_HORDE_SPECIFIC_SPELL" },
        { bit: 512, name: "SPELL_ATTR7_ALLIANCE_SPECIFIC_SPELL" },
        { bit: 1024, name: "SPELL_ATTR7_DISPEL_REMOVES_CHARGES" },
        { bit: 2048, name: "SPELL_ATTR7_CAN_CAUSE_INTERRUPT" },
        { bit: 4096, name: "SPELL_ATTR7_CAN_CAUSE_SILENCE" },
        { bit: 8192, name: "SPELL_ATTR7_NO_UI_NOT_INTERRUPTIBLE" },
        { bit: 16384, name: "SPELL_ATTR7_RECAST_ON_RESUMMON" },
        { bit: 32768, name: "SPELL_ATTR7_RESET_SWING_TIMER_AT_SPELL_START" },
        { bit: 65536, name: "SPELL_ATTR7_ONLY_IN_SPELLBOOK_UNTIL_LEARNED" },
        { bit: 131072, name: "SPELL_ATTR7_DO_NOT_LOG_PVP_KILL" },
        { bit: 262144, name: "SPELL_ATTR7_ATTACK_ON_CHARGE_TO_UNIT" },
        { bit: 524288, name: "SPELL_ATTR7_REPORT_SPELL_FAILURE_TO_UNIT_TARGET" },
        { bit: 1048576, name: "SPELL_ATTR7_NO_CLIENT_FAIL_WHILE_STUNNED_FLEEING_CONFUSED" },
        { bit: 2097152, name: "SPELL_ATTR7_RETAIN_COOLDOWN_THROUGH_LOAD" },
        { bit: 4194304, name: "SPELL_ATTR7_IGNORES_COLD_WEATHER_FLYING_REQUIREMENT" },
        { bit: 8388608, name: "SPELL_ATTR7_NO_ATTACK_DODGE" },
        { bit: 16777216, name: "SPELL_ATTR7_NO_ATTACK_PARRY" },
        { bit: 33554432, name: "SPELL_ATTR7_NO_ATTACK_MISS" },
        { bit: 67108864, name: "SPELL_ATTR7_TREAT_AS_NPC_AOE" },
        { bit: 134217728, name: "SPELL_ATTR7_BYPASS_NO_RESURRECTION_AURA" },
        { bit: 268435456, name: "SPELL_ATTR7_DO_NOT_COUNT_FOR_PVP_SCOREBOARD" },
        { bit: 536870912, name: "SPELL_ATTR7_REFLECTION_ONLY_DEFENDS" },
        { bit: 1073741824, name: "SPELL_ATTR7_CAN_PROC_FROM_SUPPRESSED_TARGET_PROCS" },
        { bit: 2147483648, name: "SPELL_ATTR7_ALWAYS_CAST_LOG" }
    ],
    procflag: [
        { bit: 0, name: "PROC_FLAG_NONE" },
        { bit: 1, name: "PROC_FLAG_KILLED" },
        { bit: 2, name: "PROC_FLAG_KILL" },
        { bit: 4, name: "PROC_FLAG_DONE_MELEE_AUTO_ATTACK" },
        { bit: 8, name: "PROC_FLAG_TAKEN_MELEE_AUTO_ATTACK" },
        { bit: 16, name: "PROC_FLAG_DONE_SPELL_MELEE_DMG_CLASS" },
        { bit: 32, name: "PROC_FLAG_TAKEN_SPELL_MELEE_DMG_CLASS" },
        { bit: 64, name: "PROC_FLAG_DONE_RANGED_AUTO_ATTACK" },
        { bit: 128, name: "PROC_FLAG_TAKEN_RANGED_AUTO_ATTACK" },
        { bit: 256, name: "PROC_FLAG_DONE_SPELL_RANGED_DMG_CLASS" },
        { bit: 512, name: "PROC_FLAG_TAKEN_SPELL_RANGED_DMG_CLASS" },
        { bit: 1024, name: "PROC_FLAG_DONE_SPELL_NONE_DMG_CLASS_POS" },
        { bit: 2048, name: "PROC_FLAG_TAKEN_SPELL_NONE_DMG_CLASS_POS" },
        { bit: 4096, name: "PROC_FLAG_DONE_SPELL_NONE_DMG_CLASS_NEG" },
        { bit: 8192, name: "PROC_FLAG_TAKEN_SPELL_NONE_DMG_CLASS_NEG" },
        { bit: 16384, name: "PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_POS" },
        { bit: 32768, name: "PROC_FLAG_TAKEN_SPELL_MAGIC_DMG_CLASS_POS" },
        { bit: 65536, name: "PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG" },
        { bit: 131072, name: "PROC_FLAG_TAKEN_SPELL_MAGIC_DMG_CLASS_NEG" },
        { bit: 262144, name: "PROC_FLAG_DONE_PERIODIC" },
        { bit: 524288, name: "PROC_FLAG_TAKEN_PERIODIC" },
        { bit: 1048576, name: "PROC_FLAG_TAKEN_DAMAGE" },
        { bit: 2097152, name: "PROC_FLAG_DONE_TRAP_ACTIVATION" },
        { bit: 4194304, name: "PROC_FLAG_DONE_MAINHAND_ATTACK" },
        { bit: 8388608, name: "PROC_FLAG_DONE_OFFHAND_ATTACK" },
        { bit: 16777216, name: "PROC_FLAG_DEATH" }        
    ],
    procspellphase: [
        { bit: 0, name: "PROC_SPELL_PHASE_NONE" },
        { bit: 1, name: "PROC_SPELL_PHASE_CAST" },
        { bit: 2, name: "PROC_SPELL_PHASE_HIT" },
        { bit: 4, name: "PROC_SPELL_PHASE_FINISH" }
    ],
    procspelltype: [
        { bit: 0, name: "PROC_SPELL_TYPE_NONE" },
        { bit: 1, name: "PROC_SPELL_TYPE_DAMAGE" },
        { bit: 2, name: "PROC_SPELL_TYPE_HEAL" },
        { bit: 4, name: "PROC_SPELL_TYPE_NO_DMG_HEAL" }
    ],
    prochit: [
        { bit: 0, name: "PROC_HIT_NONE" },
        { bit: 1, name: "PROC_HIT_NORMAL" },
        { bit: 2, name: "PROC_HIT_CRITICAL" },
        { bit: 4, name: "PROC_HIT_MISS" },
        { bit: 8, name: "PROC_HIT_FULL_RESIST" },
        { bit: 16, name: "PROC_HIT_DODGE" },
        { bit: 32, name: "PROC_HIT_PARRY" },
        { bit: 64, name: "PROC_HIT_BLOCK" },
        { bit: 128, name: "PROC_HIT_EVADE" },
        { bit: 256, name: "PROC_HIT_IMMUNE" },
        { bit: 512, name: "PROC_HIT_DEFLECT" },
        { bit: 1024, name: "PROC_HIT_ABSORB" },
        { bit: 2048, name: "PROC_HIT_REFLECT" },
        { bit: 4096, name: "PROC_HIT_INTERRUPT" },
        { bit: 8192, name: "PROC_HIT_FULL_BLOCK" }
    ],
    procattr: [
        { bit: 1, name: "PROC_ATTR_REQ_EXP_OR_HONOR" },
        { bit: 2, name: "PROC_ATTR_TRIGGERED_CAN_PROC" },
        { bit: 4, name: "PROC_ATTR_REQ_MANA_COST" },
        { bit: 8, name: "PROC_ATTR_REQ_SPELLMOD" },
        { bit: 16, name: "PROC_ATTR_USE_STACKS_FOR_CHARGES" },
        { bit: 128, name: "PROC_ATTR_REDUCE_PROC_60" },
        { bit: 256, name: "PROC_ATTR_CANT_PROC_FROM_ITEM_CAST" }
    ],
    procdisableeffects: [
        { bit: 1, name: "DISABLE_EFFECT_0" },
        { bit: 2, name: "DISABLE_EFFECT_1" },
        { bit: 4, name: "DISABLE_EFFECT_2" }
    ],
    spellstackrules: [
        { bit: 0, name: "SPELL_GROUP_STACK_RULE_DEFAULT" },
        { bit: 1, name: "SPELL_GROUP_STACK_RULE_EXCLUSIVE" },
        { bit: 2, name: "SPELL_GROUP_STACK_FLAG_NOT_SAME_CASTER" },
        { bit: 4, name: "SPELL_GROUP_STACK_FLAG_FLAGGED" },
        { bit: 8, name: "SPELL_GROUP_STACK_FLAG_NEVER_STACK" },
        { bit: 16, name: "SPELL_GROUP_STACK_FLAG_EFFECT_EXCLUSIVE" },
        // { bit: 32, name: "SPELL_GROUP_STACK_FLAG_MAX" },
        { bit: 256, name: "SPELL_GROUP_STACK_FLAG_FORCED_STRONGEST (internal use)" },
        { bit: 512, name: "SPELL_GROUP_STACK_FLAG_FORCED_WEAKEST (internal use)" }               
    ],
    gameobjectflags: [
        { bit: 1, name: "GO_FLAG_IN_USE" },
        { bit: 2, name: "GO_FLAG_LOCKED" },
        { bit: 4, name: "GO_FLAG_INTERACT_COND" },
        { bit: 8, name: "GO_FLAG_TRANSPORT" },
        { bit: 16, name: "GO_FLAG_NOT_SELECTABLE" },
        { bit: 32, name: "GO_FLAG_NODESPAWN" },
        { bit: 64, name: "GO_FLAG_TRIGGERED" },
        { bit: 512, name: "GO_FLAG_DAMAGED" },
        { bit: 1024, name: "GO_FLAG_DESTROYED" }
    ],
    gameobjectdynamiclowflags: [
        { bit: 1, name: "GO_DYNFLAG_LO_ACTIVATE" },
        { bit: 2, name: "GO_DYNFLAG_LO_ANIMATE" },
        { bit: 4, name: "GO_DYNFLAG_LO_NO_INTERACT" },
        { bit: 8, name: "GO_DYNFLAG_LO_SPARKLE" },
        { bit: 16, name: "GO_DYNFLAG_LO_STOPPED" }
    ],
    questflags: [
        { bit: 1, name: "QUEST_FLAGS_STAY_ALIVE" },
        { bit: 2, name: "QUEST_FLAGS_PARTY_ACCEPT" },
        { bit: 4, name: "QUEST_FLAGS_EXPLORATION" },
        { bit: 8, name: "QUEST_FLAGS_SHARABLE" },
        { bit: 16, name: "QUEST_FLAGS_HAS_CONDITION" },
        { bit: 32, name: "QUEST_FLAGS_HIDE_REWARD_POI" },
        { bit: 64, name: "QUEST_FLAGS_RAID" },
        { bit: 128, name: "QUEST_FLAGS_TBC" },
        { bit: 256, name: "QUEST_FLAGS_NO_MONEY_FROM_XP" },
        { bit: 512, name: "QUEST_FLAGS_HIDDEN_REWARDS" },
        { bit: 1024, name: "QUEST_FLAGS_TRACKING" },
        { bit: 2048, name: "QUEST_FLAGS_DEPRECATE_REPUTATION" },
        { bit: 4096, name: "QUEST_FLAGS_DAILY" },
        { bit: 8192, name: "QUEST_FLAGS_FLAGS_PVP" },
        { bit: 16384, name: "QUEST_FLAGS_UNAVAILABLE" },
        { bit: 32768, name: "QUEST_FLAGS_WEEKLY" },
        { bit: 65536, name: "QUEST_FLAGS_AUTOCOMPLETE" },
        { bit: 131072, name: "QUEST_FLAGS_DISPLAY_ITEM_IN_TRACKER" },
        { bit: 262144, name: "QUEST_FLAGS_OBJ_TEXT" },
        { bit: 524288, name: "QUEST_FLAGS_AUTO_ACCEPT" }
    ],
    specialflags: [
        { bit: 1, name: "SPECIAL_FLAGS_REPEATABLE" },
        { bit: 2, name: "SPECIAL_FLAGS_EXTERNAL_EVENT" },
        { bit: 4, name: "SPECIAL_FLAGS_AUTO_ACCEPT" },
        { bit: 8, name: "SPECIAL_FLAGS_DUNGEON_FINDER" },
        { bit: 16, name: "SPECIAL_FLAGS_MONTHLY" },
        { bit: 32, name: "SPECIAL_FLAGS_REQUIRED_NPC_GO_KILLCREDIT" },
        { bit: 64, name: "SPECIAL_FLAGS_NO_SHARED_REPUTATION" },
        { bit: 128, name: "SPECIAL_FLAGS_FAIL_INDEPENDENT" },
        { bit: 256, name: "SPECIAL_FLAGS_NO_LOREMASTER_COUNT" }        
    ],
    itemflags: [
        { bit: 1, name: "ITEM_FLAG_NO_PICKUP" },
        { bit: 2, name: "ITEM_FLAG_CONJURED" },
        { bit: 4, name: "ITEM_FLAG_OPENABLE" },
        { bit: 8, name: "ITEM_FLAG_HEROIC_TOOLTIP" },
        { bit: 16, name: "ITEM_FLAG_DEPRECATED" },
        { bit: 32, name: "ITEM_FLAG_CANNOT_BE_DESTROYED" },
        { bit: 64, name: "ITEM_FLAG_PLAYERCAST" },
        { bit: 128, name: "ITEM_FLAG_NO_EQUIP_COOLDOWN" },
        { bit: 256, name: "ITEM_FLAG_MULTI_LOOT_QUEST" },
        { bit: 512, name: "ITEM_FLAG_WRAPPER" },
        { bit: 1024, name: "ITEM_FLAG_USES_RESOURCES" },
        { bit: 2048, name: "ITEM_FLAG_PARTY_LOOT" },
        { bit: 4096, name: "ITEM_FLAG_REFUNDABLE" },
        { bit: 8192, name: "ITEM_FLAG_CHARTER" },
        { bit: 16384, name: "ITEM_FLAG_HAS_TEXT" },
        { bit: 32768, name: "ITEM_FLAG_NO_DISENCHANT" },
        { bit: 65536, name: "ITEM_FLAG_REAL_DURATION" },
        { bit: 131072, name: "ITEM_FLAG_NO_CREATOR" },
        { bit: 262144, name: "ITEM_FLAG_CAN_BE_PROSPECTED" },
        { bit: 524288, name: "ITEM_FLAG_UNIQUE_EQUIPPED" },
        { bit: 1048576, name: "ITEM_FLAG_IGNORE_FOR_AURAS" },
        { bit: 2097152, name: "ITEM_FLAG_CAN_BE_USED_IN_ARENA" },
        { bit: 4194304, name: "ITEM_FLAG_THROWABLE" },
        { bit: 8388608, name: "ITEM_FLAG_CAN_BE_USED_IN_SHAPESHIFT" },
        { bit: 16777216, name: "ITEM_FLAG_HAS_QUEST_GLOW" },
        { bit: 33554432, name: "ITEM_FLAG_PROFESSION_RECIPE" },
        { bit: 67108864, name: "ITEM_FLAG_CANNOT_BE_USED_IN_ARENA" },
        { bit: 134217728, name: "ITEM_FLAG_BIND_TO_ACCOUNT" },
        { bit: 268435456, name: "ITEM_FLAG_NO_REAGENT_COST" },
        { bit: 536870912, name: "ITEM_FLAG_MILLABLE" },
        { bit: 1073741824, name: "ITEM_FLAG_REPORT_TO_GUILD_CHAT" },
        { bit: 2147483648, name: "ITEM_FLAG_NO_PROGRESSIVE_LOOT" }        
    ],
    flagsextra: [
        { bit: 1, name: "Horde_Only" },
        { bit: 2, name: "Alliance_Only" },
        { bit: 4, name: "USES_EXTENDEDCOST" },
        { bit: 256, name: "NEED_ROLL_DISABLED" },
        { bit: 512, name: "NEED_ROLL_DISABLED" },
        { bit: 16384, name: "HAS_NORMAL_PRICE" },
        { bit: 131072, name: "BNET_ACCOUNT_BOUND" },
        { bit: 2097152, name: "CANNOT_BE_TRANSMOG" },
        { bit: 4194304, name: "CANNOT_TRANSMOG" },
        { bit: 8388608, name: "CAN_TRANSMOG" }               
    ],
    bagfamily: [
        { bit: 1, name: "Arrows" },
        { bit: 2, name: "Bullets" },
        { bit: 4, name: "Soul_Shard" },
        { bit: 8, name: "Leatherworking_Supplies" },
        { bit: 16, name: "Inscription_Supplies" },
        { bit: 32, name: "Herbs" },
        { bit: 64, name: "Enchanting_Supplies" },
        { bit: 128, name: "Engineering_Supplies" },
        { bit: 256, name: "Keys" },
        { bit: 512, name: "Gems" },
        { bit: 1024, name: "Mining_Supplies" },
        { bit: 2048, name: "Soulbound_Equipment" },
        { bit: 4096, name: "Vanity_Pets" },
        { bit: 8192, name: "Currency_Tokens" },
        { bit: 16384, name: "Quest_Items" }        
    ],
    flagscustom: [
        { bit: 1, name: "ITEM_FLAGS_CU_DURATION_REAL_TIME" },
        { bit: 2, name: "ITEM_FLAGS_CU_IGNORE_QUEST_STATUS" },
        { bit: 4, name: "ITEM_FLAGS_CU_FOLLOW_LOOT_RULES" }        
    ],
};