const flagCategories = {
    unit: [
        { name: "npcflag", value: "npcflag" },
        { name: "unit_flags", value: "unit_flags" },
        { name: "unit_flags2", value: "unit_flags2" },
        { name: "type_flags", value: "type_flags" },
        { name: "flags_extra", value: "flags_extra" },
        { name: "unit_dynflags", value: "unit_dynflag" },
        { name: "mechanic_immune_mask (legacy)", value: "mechanic_immune_mask" },
        { name: "spell_school_immune_mask (legacy)", value: "spellschoolmask" },
        { name: "racemask", value: "racemask" },
        { name: "classmask", value: "classmask" },
    ],
    immunities: [
        { name: "MechanicsMask", value: "MechanicsMask" },
        { name: "SchoolMask", value: "SchoolMask" },
        { name: "DispelTypeMask", value: "DispelTypeMask" },
    ],
    gameobject: [
        { name: "GameObjectFlags", value: "gameobjectflags" },
        { name: "GameObjectDynamicLowFlags", value: "gameobjectdynamiclowflags" }
    ],
    spell: [
        { name: "SpellAttr0", value: "spellattr0" },
        { name: "SpellAttr1", value: "spellattr1" },
        { name: "SpellAttr2", value: "spellattr2" },
        { name: "SpellAttr3", value: "spellattr3" },
        { name: "SpellAttr4", value: "spellattr4" },
        { name: "SpellAttr5", value: "spellattr5" },
        { name: "SpellAttr6", value: "spellattr6" },
        { name: "SpellAttr7", value: "spellattr7" },
        { name: "SpellCustomAttr", value: "spellcustomattr" },
        { name: "SpellSchoolMask", value: "spellschoolmask" },
        { name: "DispelMask", value: "dispelmask" },
        { name: "ProcFlag", value: "procflag" },
        { name: "ProcSpellType", value: "procspelltype" },
        { name: "ProcSpellPhase", value: "procspellphase" },
        { name: "ProcHit", value: "prochit" },
        { name: "ProcAttr", value: "procattr" },
        { name: "ProcDisableEffects", value: "procdisableeffects" },
        { name: "SpellStackRules", value: "spellstackrules" },
        { name: "InterruptFlags", value: "InterruptFlags" },
        { name: "AuraInterruptFlags", value: "AuraInterruptFlags" },
        { name: "ChannelInterruptFlags", value: "ChannelInterruptFlags" },
        { name: "Targets", value: "Targets" },
        { name: "FacingCasterFlags", value: "FacingCasterFlags" },
        { name: "ShapeshiftMask / ShapeshiftExclude", value: "ShapeshiftMask" },
        { name: "TargetCreatureType", value: "TargetCreatureType" },
    ],
    quest: [
        { name: "QuestFlags", value: "questflags" },
        { name: "SpecialFlags", value: "specialflags" }
    ],
    item: [
        { name: "ItemFlags", value: "itemflags" },
        { name: "FlagsExtra", value: "flagsextra" },
        { name: "BagFamily", value: "bagfamily" },
        { name: "FlagsCustom", value: "flagscustom" },
    ],
    smartai: [
        { name: "event_flags", value: "event_flags" },
        { name: "Cast flags (SMART_ACTION_CAST)", value: "SmartCastFlags" },
    ],
    other: [
    ],
}
